spring.profiles.active=dev
#logging.level.net.engineeringdigest.journalApp=DEBUG
#logging.level.root=ERROR


weather_api_key=228b84d25643804c81d8cd19f648199b

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sharmayash17052000@gmail.com
spring.mail.password=enka agsa fehk jzxj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer Configuration
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=abc

# Allow JSON Deserialization for your model package
spring.json.trusted.packages=net.engineeringdigest.journalApp.model

spring.security.oauth2.client.registration.google.client-id=23443228782-o1rok9f5f8c77v4c39ernanv9b5fq7hd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

